"""
Writer Agent
Synthesizes all research results into a coherent markdown or txt report.
"""

from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

from state import AgentState
from datetime import datetime
import os
from dotenv import load_dotenv
load_dotenv()
from ConnectionManager import manager
from .loadModel import llm

    


# Markdown
# SYSTEM_PROMPT = """You are a technical writer. Given research notes on a topic, 
# write a detailed, well-structured markdown report.

# Include:
# - A title (# heading)
# - An executive summary (4-5 sentences covering the full scope)
# - A detailed section for each research area with thorough explanation, examples, and analysis
# - A "Key Takeaways" section with bullet points
# - A conclusion with forward-looking insights

# Go deep on each section — aim for at least 3-4 paragraphs per topic.
# Write in a professional but accessible tone. Use markdown formatting including
# subheadings (###) within sections where appropriate."""

# txt format
SYSTEM_PROMPT = """You are a technical writer. Given research notes on a topic,
write a detailed, well-structured report in plain text format.

Include:
- A title in all caps
- An executive summary (4-5 sentences covering the full scope)
- A detailed section for each research area with thorough explanation, examples, and analysis
- A KEY TAKEAWAYS section
- A conclusion with forward-looking insights

Go deep on each section — aim for at least 3-4 paragraphs per topic.
Use plain text only. No markdown, no asterisks, no bullet dashes.
Enclose all section headings with hashtags, like: #SECTION HEADING#
Use blank lines to separate sections."""


async def writer_node(state: AgentState) -> AgentState:
    # print("✍️  Writer: Synthesizing report...")
    await manager.broadcast({"message" : "Writer: Synthesizing report..."})
    
    research_blob = "\n\n".join(state["research_results"])

    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=(
            f"Original query: {state['query']}\n\n"
            f"Research notes:\n{research_blob}"
        ))
    ]

    response = llm.invoke(messages)

    # for markdown
    # Prepend metadata
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    # report = f"> Generated by multi-agent research system | {timestamp}\n\n"
    # report += response.content.strip()

    # for txt
    report = f"Generated by multi-agent research system | {timestamp}\n"
    report += "=" * 60 + "\n\n"
    report += response.content.strip()
    return {**state, "report": report}
