"""
Writer Agent
Synthesizes all research results into a coherent markdown report.
"""

from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage
from state import AgentState
from datetime import datetime
import os
from dotenv import load_dotenv
load_dotenv()


llm = ChatOllama(model=os.getenv('MODEL'), temperature=0)

SYSTEM_PROMPT = """You are a technical writer. Given research notes on a topic, 
write a detailed, well-structured markdown report.

Include:
- A title (# heading)
- An executive summary (4-5 sentences covering the full scope)
- A detailed section for each research area with thorough explanation, examples, and analysis
- A "Key Takeaways" section with bullet points
- A conclusion with forward-looking insights

Go deep on each section — aim for at least 3-4 paragraphs per topic.
Write in a professional but accessible tone. Use markdown formatting including
subheadings (###) within sections where appropriate."""


def writer_node(state: AgentState) -> AgentState:
    print("✍️  Writer: Synthesizing report...")

    research_blob = "\n\n".join(state["research_results"])

    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=(
            f"Original query: {state['query']}\n\n"
            f"Research notes:\n{research_blob}"
        ))
    ]

    response = llm.invoke(messages)

    # Prepend metadata
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    report = f"> Generated by multi-agent research system | {timestamp}\n\n"
    report += response.content.strip()

    return {**state, "report": report}
